// Libros de dominio público y recursos educativos de acceso libre

function _p(t1, t2, aut, bg, ac, ic) {
  const t2line = t2 ? `<text x="18" y="237" font-family="Georgia,serif" font-size="13" font-weight="bold" fill="white">${t2}</text>` : '';
  const yaut = t2 ? 255 : 239;
  const s = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 280" width="200" height="280"><rect width="200" height="280" fill="${bg}"/><rect width="6" height="280" fill="${ac}"/><text x="100" y="155" text-anchor="middle" font-size="88" font-family="Georgia,serif" fill="${ac}" opacity=".18">${ic}</text><line x1="18" y1="202" x2="182" y2="202" stroke="${ac}" stroke-width="1.5" opacity=".6"/><text x="18" y="218" font-family="Georgia,serif" font-size="13" font-weight="bold" fill="white">${t1}</text>${t2line}<text x="18" y="${yaut}" font-family="Georgia,serif" font-size="10" fill="${ac}">${aut}</text></svg>`;
  return 'data:image/svg+xml,' + encodeURIComponent(s);
}

const LIBROS_PRECARGADOS = [

  // ── EDUCACIÓN ──────────────────────────────────────────────────────────────

  {
    id: 'pre_edu_comenio',
    titulo: 'Didáctica Magna',
    autor: 'Juan Amós Comenio',
    paginas: [
      { texto: 'DIDÁCTICA MAGNA\nJuan Amós Comenio — 1638\n\n"El arte de enseñar todo a todos"\n\nPRÓLOGO AL LECTOR\n\nNosotros nos atrevemos a prometer una Didáctica Magna, esto es, un artificio universal para enseñar todo a todos con solidez, agrado y brevedad. En suma: una escuela donde todos aprendan todo bien, donde haya menos ruido, menos hastiados, menos trabajo inútil; sino más tiempo libre, más gozo y más seguro provecho.', nota: '' },
      { texto: 'CAPÍTULO I — EL HOMBRE ES LA CRIATURA MÁS ELEVADA\n\nEl hombre es la criatura más perfecta, la más excelente y admirable de todas las criaturas visibles. Esto aparece patente: en su origen, pues fue formado de una manera especial por la mano de Dios, recibió soplo del espíritu divino y fue creado a imagen y semejanza de Dios;\n\nen su dignidad, pues se le encargó el gobierno de las demás criaturas;\n\nen su fin, pues se le destinó a ser partícipe de la felicidad divina con Dios durante toda la eternidad.\n\nSiendo esto así, es evidente que el hombre necesita ser formado para que pueda cumplir verdaderamente su destino.', nota: '' },
      { texto: 'CAPÍTULO VI — SI LA JUVENTUD DEBE SER EDUCADA EN COMÚN EN LAS ESCUELAS\n\nSería conveniente que hubiera escuelas para la formación de la juventud en las ciudades, aldeas y lugares.\nY esto porque:\n\n1. Un maestro solo puede instruir a muchos alumnos con menos trabajo que si instruyese a cada uno en particular; el trabajo de muchos reúne más fuerzas.\n\n2. Cuando los alumnos trabajan juntos, se estimulan y despiertan mutuamente. El emularse y el compararse fomenta el deseo de aprender.\n\n3. En una escuela correctamente organizada, los maestros enseñan más y los niños aprenden más con menos esfuerzo.', nota: '' },
      { texto: 'CAPÍTULO X — LA ENSEÑANZA ESCOLAR DEBE SER UN VERDADERO DELEITE\n\nSi el estudio se convierte en un peso para los estudiantes, si les hace la vida intolerable, si los cansa y los aburre, la culpa es nuestra. Porque no hemos sabido hacerlo agradable.\n\nLa naturaleza misma nos enseña: el niño que juega aprende más que el que es forzado a estudiar. Porque en el juego hay placer, y donde hay placer, el espíritu se abre.\n\nPor tanto: que los niños entren en la escuela como entran en un jardín de delicias. Que los libros sean como fuentes de las que brota el saber con claridad y sin esfuerzo.', nota: '' },
      { texto: 'CAPÍTULO XVII — LOS FUNDAMENTOS DE LA FACILIDAD EN LA ENSEÑANZA\n\nLa naturaleza espera el momento oportuno. El jardinero no puede hacer que el árbol crezca más rápido de lo que la naturaleza permite; pero puede preparar el terreno, podar, regar.\n\nAsí el maestro: no puede forzar el desarrollo del alumno, pero puede preparar el ambiente, eliminar obstáculos y estimular el proceso natural.\n\nFUNDAMENTOS:\n1. Comenzar temprano, antes de que la mente se endurezca.\n2. Proceder de lo simple a lo complejo.\n3. Proceder de lo conocido a lo desconocido.\n4. No enseñar demasiadas cosas a la vez.\n5. Avanzar despacio pero sin pausa.', nota: '' },
      { texto: 'CAPÍTULO XVIII — LOS FUNDAMENTOS DE LA SOLIDEZ EN LA ENSEÑANZA\n\nEL ORDEN es la base de todo. Como en la naturaleza todo sigue un orden —las estaciones, el crecimiento de los seres vivos— así también en la enseñanza.\n\nNada debe enseñarse sin una razón clara. El maestro que no puede explicar por qué enseña algo, no debería enseñarlo.\n\nLa PRÁCTICA debe seguir siempre a la teoría. El alumno no aprende verdaderamente hasta que puede aplicar lo aprendido.\n\nLa REPETICIÓN es necesaria pero no debe ser mecánica: repetir comprendiendo, en contextos distintos, con aplicaciones variadas.', nota: '' },
    ],
    portada: _p('Didáctica Magna','','Juan Amós Comenio','#1a3a5c','#f0c040','◆'), creado: 'Clásico Pedagogía 1638', ultimaPag: 0, marcadores: [], palabras: 520, fuente: 'precargado'
  },

  {
    id: 'pre_edu_rousseau',
    titulo: 'Emilio o De la educación',
    autor: 'Jean-Jacques Rousseau',
    paginas: [
      { texto: 'EMILIO O DE LA EDUCACIÓN\nJean-Jacques Rousseau — 1762\n\nLIBRO PRIMERO\n\nTodo está bien al salir de las manos del Autor de la naturaleza; todo degenera entre las manos del hombre. Obliga a una tierra a nutrir los productos de otra, a un árbol a llevar los frutos de otro; mezcla y confunde los climas, los elementos y las estaciones; mutila su perro, su caballo, su esclavo; lo trastorna todo, lo desfigura todo; ama la deformidad, los monstruos; no quiere nada tal como lo ha hecho la naturaleza, ni al mismo hombre.', nota: '' },
      { texto: 'Las plantas se forman por el cultivo y los hombres por la educación. Si el hombre naciese grande y fuerte, su talla y su fuerza le serían inútiles hasta que aprendiera a servirse de ellas; le serían perjudiciales, pues al no dejar que los demás pensaran en atenderle, le dejarían morir de miseria antes de conocer sus necesidades.\n\nNacemos débiles, necesitamos fuerzas; nacemos desprovistos de todo, necesitamos asistencia; nacemos estúpidos, necesitamos juicio. Todo lo que no tenemos en el nacimiento y que necesitamos siendo adultos, nos es dado por la educación.', nota: '' },
      { texto: 'LIBRO SEGUNDO — INFANCIA\n\nLa naturaleza quiere que los niños sean niños antes de ser hombres. Si queremos pervertir ese orden, produciremos frutos tempranos que no tendrán ni madurez ni sabor.\n\nAmad la infancia; favoreced sus juegos, sus placeres, su amable instinto. ¿Quién de vosotros no ha tenido alguna vez nostalgia de aquella edad en que la risa está siempre en los labios?\n\nEl mayor, el más importante, el más útil precepto de toda educación no es ganar tiempo, sino perderlo.', nota: '' },
      { texto: 'LIBRO TERCERO — PUBERTAD\n\nEn general, no enseñéis al niño la ciencia, sino a adquirirla por sí mismo. Si en lugar de hacer aprender la ciencia en los libros, la inventamos, sería mejor.\n\nEl niño que trabaja en resolver sus propios problemas desarrolla su razón mucho mejor que el que recibe soluciones ya elaboradas.\n\nLa mente curiosa necesita ser guiada, no llenada. El maestro que responde todas las preguntas mata la curiosidad. El que sabe cuándo responder y cuándo dejar al alumno buscar, siembra el amor por el conocimiento.', nota: '' },
      { texto: 'LIBRO CUARTO — ADOLESCENCIA\n\nEntramos en el orden moral; acabamos de dar un segundo nacimiento al hombre. Hasta ahora no teníamos más que un ser individual; ahora nos interesa el hombre en sus relaciones con los demás.\n\nLas primeras nociones de bien y de mal no son racionales sino afectivas. Se comprende antes de poder explicar. El corazón del niño es sensible antes de que su razón sea activa.\n\nPor eso, la educación moral debe comenzar por el ejemplo, no por el discurso. El niño que ve bondad, aprende bondad. El que ve justicia, aprende a ser justo.', nota: '' },
      { texto: 'LIBRO QUINTO — CONCLUSIONES\n\nNo sé si vuestro alumno llegará o no a ser un hombre virtuoso, sabio, feliz. Pero sé que a vuestra edad podrá juzgar, conocer, amar todo lo que es bueno, bello, amable.\n\nHe intentado describir un ser de razón. He intentado mostrar cómo este ser puede formarse. Me quedan muchas cosas por decir; pero lo esencial está dicho.\n\nQue la naturaleza sea vuestra guía. Que el respeto al niño sea vuestra regla. Que la libertad vigilada sea vuestro método. Y que el amor a la humanidad sea vuestro fin.', nota: '' },
    ],
    portada: _p('Emilio o De la','educación','Jean-Jacques Rousseau','#2d5016','#a8d58a','○'), creado: 'Clásico Pedagogía 1762', ultimaPag: 0, marcadores: [], palabras: 560, fuente: 'precargado'
  },

  {
    id: 'pre_edu_dewey',
    titulo: 'Experiencia y Educación',
    autor: 'John Dewey',
    paginas: [
      { texto: 'EXPERIENCIA Y EDUCACIÓN\nJohn Dewey — 1938\n\nCAPÍTULO I — EDUCACIÓN TRADICIONAL Y PROGRESISTA\n\nLa historia del pensamiento educativo está marcada por la oposición entre dos concepciones. La educación tradicional insiste en la transmisión de conocimientos y estándares del pasado; la educación progresista insiste en la expresión y el cultivo de la individualidad.\n\nPero una buena educación no puede reducirse a ninguno de esos extremos. El verdadero problema es encontrar qué cualidades de la experiencia conducen al crecimiento, y cuáles bloquean el desarrollo futuro.', nota: '' },
      { texto: 'CAPÍTULO II — LA NECESIDAD DE UNA TEORÍA DE LA EXPERIENCIA\n\nNinguna experiencia vive y muere para sí sola. Toda experiencia recoge algo de las que han pasado antes, y modifica en cierta medida la calidad de las que vienen después.\n\nEl principio de continuidad de la experiencia significa que toda experiencia toma algo de las experiencias anteriores y modifica, de algún modo, las experiencias subsiguientes.\n\nEl segundo principio es el de interacción: una experiencia se produce siempre en la doble relación del individuo con su ambiente. Toda genuina experiencia tiene un aspecto activo y uno pasivo.', nota: '' },
      { texto: 'CAPÍTULO III — CRITERIOS DE LA EXPERIENCIA\n\nUna experiencia puede ser inmediatamente agradable y sin embargo promover malos hábitos; una experiencia puede ser desagradable y sin embargo enriquecer el crecimiento.\n\nLa pregunta no es si la experiencia es agradable, sino si es educativa en el sentido de conducir al crecimiento.\n\nEl educador responsable no solo considera cuáles son las condiciones que producen experiencias enriquecedoras, sino también cuáles de estas experiencias enriquecedoras conducen a experiencias futuras igualmente valiosas.', nota: '' },
      { texto: 'CAPÍTULO IV — CONTROL SOCIAL\n\nEn la educación tradicional el control era externo: el maestro imponía las normas. En la educación progresista el riesgo es el opuesto: la ausencia de control.\n\nPero existe un tercer camino: el control social que emerge del trabajo cooperativo. Cuando los alumnos participan en una empresa conjunta, las propias exigencias de la situación imponen el control.\n\nEl maestro no pierde su rol de autoridad, pero esa autoridad emerge de su mayor experiencia y conocimiento, no de su posición jerárquica. El buen maestro es el que logra que el alumno quiera aprender.', nota: '' },
      { texto: 'CAPÍTULO V — LA NATURALEZA DE LA LIBERTAD\n\nLa libertad que importa es la intelectual: la libertad de observar y juzgar que se ejerce al servicio de propósitos que son intrínsecamente valiosos.\n\nLa libertad de movimiento, de trabajo manual, de expresión no es un fin en sí misma. Es un medio para lograr la libertad del espíritu. Quien confunde las dos, pone los medios en lugar del fin.\n\nEl alumno que puede hacer lo que quiere sin dirección ni propósito no es libre: es esclavo de sus impulsos momentáneos. La verdadera libertad incluye la capacidad de elegir con criterio.', nota: '' },
      { texto: 'CAPÍTULO VI — EL PROPÓSITO Y EL PLAN\n\nEl propósito auténtico nace siempre de un impulso. Pero hay una gran diferencia entre un impulso y un propósito. Un propósito supone observación de las condiciones del ambiente; supone conocimiento de lo que ha ocurrido en situaciones similares en el pasado; supone juicio que pone en relación lo observado con lo que se recuerda.\n\nEl rol del maestro es ayudar al alumno a transformar sus impulsos en propósitos, sus deseos en planes. Y eso requiere diálogo, guía, y la creación de condiciones que hagan posible pensar.', nota: '' },
    ],
    portada: _p('Experiencia y','Educación','John Dewey','#1a237e','#7986cb','⊕'), creado: 'Clásico Pedagogía 1938', ultimaPag: 0, marcadores: [], palabras: 540, fuente: 'precargado'
  },

  {
    id: 'pre_edu_delors',
    titulo: 'La educación encierra un tesoro — UNESCO',
    autor: 'Jacques Delors (UNESCO)',
    paginas: [
      { texto: 'LA EDUCACIÓN ENCIERRA UN TESORO\nInforme a la UNESCO de la Comisión Internacional sobre la Educación para el Siglo XXI\nJacques Delors — 1996\n\nFRENTE A LOS MÚLTIPLES DESAFÍOS DEL PORVENIR\n\nLa educación constituye un instrumento indispensable para que la humanidad pueda progresar hacia los ideales de paz, libertad y justicia social. La Comisión desea transmitir un mensaje esperanzador: la educación puede contribuir a lograr un mundo más seguro, más sano, más próspero y, al mismo tiempo, más solidario.', nota: '' },
      { texto: 'LOS CUATRO PILARES DE LA EDUCACIÓN\n\nAprender a conocer: Este tipo de aprendizaje tiende menos a la adquisición de conocimientos clasificados que al dominio de los instrumentos mismos del saber. Combina una cultura general amplia con la posibilidad de profundizar los conocimientos en un pequeño número de materias. Supone también aprender a aprender.\n\nAprender a hacer: Aprender a conocer y aprender a hacer son en gran medida indisociables. Pero lo segundo está más vinculado a la cuestión de la formación profesional: ¿cómo enseñar al alumno a poner en práctica sus conocimientos?', nota: '' },
      { texto: 'Aprender a vivir juntos: Sin duda, este aprendizaje constituye una de las principales empresas de la educación contemporánea. La violencia que impera en el mundo contradice la esperanza que algunos depositaron en el progreso de la humanidad.\n\nLa educación tiene una doble misión: enseñar la diversidad de la especie humana y contribuir a una toma de conciencia de las semejanzas y la interdependencia entre todos los seres humanos.\n\nAprender a ser: La educación debe contribuir al desarrollo global de cada persona: cuerpo y mente, inteligencia, sensibilidad, sentido estético, responsabilidad individual, espiritualidad.', nota: '' },
      { texto: 'EL ROL DEL DOCENTE\n\nTodo el mundo conviene en que es necesario mejorar la calidad y la motivación del personal docente. El papel del maestro no consiste solamente en transmitir información ni siquiera conocimientos, sino en presentarlos en forma de problemática, situándolos en un contexto y poniendo los problemas en perspectiva.\n\nEl maestro tiene que entablar un diálogo con el alumno y tomar en consideración sus argumentos. El buen docente está atento a sus alumnos: escucha, observa, y adapta su enseñanza a las necesidades reales del grupo.', nota: '' },
      { texto: 'LA EDUCACIÓN A LO LARGO DE TODA LA VIDA\n\nLa educación a lo largo de la vida se presenta como una de las llaves de acceso al siglo XXI. Esta noción va más allá de la distinción tradicional entre educación inicial y educación permanente, y responde al reto de un mundo que cambia rápidamente.\n\nEsta necesidad persiste por lo demás en la vida adulta, a medida que van surgiendo nuevas exigencias: adaptarse a los cambios en el mercado de trabajo, comprender mejor la evolución del mundo, vivir de una manera más satisfactoria y participar activamente en la vida social y política.', nota: '' },
      { texto: 'LA EDUCACIÓN Y LA COHESIÓN SOCIAL\n\nEs preciso que la educación contribuya a la cohesión social: frente a las fuerzas centrífugas que amenazan la sociedad, la educación debe ser un factor de integración.\n\nLa escuela debe ser el lugar donde los niños aprendan a vivir juntos, a comprender al otro en su diversidad, a resolver los conflictos de manera pacífica, a valorar los derechos humanos.\n\nConclusión: la educación es la utopía necesaria. Sin ella, nada de lo que los hombres anhelan —la paz, la justicia, la prosperidad compartida— es posible.', nota: '' },
    ],
    portada: _p('La educación','encierra un tesoro','Jacques Delors / UNESCO','#00695c','#80cbc4','★'), creado: 'UNESCO 1996', ultimaPag: 0, marcadores: [], palabras: 510, fuente: 'precargado'
  },

  {
    id: 'pre_edu_freire',
    titulo: 'Pedagogía del Oprimido',
    autor: 'Paulo Freire',
    paginas: [
      { texto: 'PEDAGOGÍA DEL OPRIMIDO\nPaulo Freire — 1968\n\nCAPÍTULO 1 — JUSTIFICACIÓN\n\nLa presente investigación busca plantear de manera objetiva la situación de violencia en que se encontraban los hombres oprimidos y su pedagogía.\n\nEl ser humano es un ser de relaciones y no solo de contactos; no solo está en el mundo sino con el mundo. El estar con el mundo resultante de su apertura a la realidad le posibilita relacionarse con ella de una manera que, a los animales, su inmersión en la realidad no les es posible hacer.', nota: '' },
      { texto: 'LA CONCEPCIÓN BANCARIA DE LA EDUCACIÓN\n\nEn la concepción bancaria, el educador conduce a los educandos a la memorización mecánica del contenido narrado. Los transforma en "vasijas", en recipientes que deben ser "llenados" por el educador.\n\nEn la concepción bancaria:\n— el educador educa y los educandos son educados;\n— el educador sabe y los educandos no saben;\n— el educador piensa y los educandos son pensados;\n— el educador habla y los educandos escuchan;\n— el educador prescribe y los educandos siguen la prescripción.', nota: '' },
      { texto: 'LA EDUCACIÓN PROBLEMATIZADORA\n\nLa educación que se impone a quienes verdaderamente se comprometen con la liberación no puede fundarse en una comprensión de los hombres como seres vacíos a quienes el mundo "llena" de contenidos.\n\nLa educación problematizadora, de carácter reflexivo, implica un constante acto de desvelamiento de la realidad. La reflexión y la acción de los hombres sobre el mundo para transformarlo.\n\nEsta educación no considera al educando un receptor pasivo, sino un co-investigador con el educador.', nota: '' },
      { texto: 'EL DIÁLOGO\n\nNo es posible el diálogo entre los que quieren pronunciar el mundo y los que no quieren hacerlo. El diálogo es el encuentro amoroso de los hombres que, mediatizados por el mundo, lo pronuncian y lo transforman.\n\nEl diálogo exige:\n— amor al mundo y a los hombres;\n— humildad (el que no ama no puede crear diálogo);\n— fe en los hombres;\n— esperanza;\n— pensamiento crítico.\n\nSin estas condiciones, lo que existe es comunicación vertical, no diálogo.', nota: '' },
      { texto: 'CAPÍTULO 3 — LA DIALOGICIDAD\n\nDecir la palabra verdadera es transformar el mundo. Existir humanamente es pronunciar el mundo, transformarlo. El mundo pronunciado, a su vez, retorna problematizado a los que lo pronuncian, exigiendo de ellos un nuevo pronunciamiento.\n\nLos hombres no se hacen en el silencio, sino en la palabra, en el trabajo, en la acción-reflexión.\n\nPor esto, el diálogo es una exigencia existencial. Y si el diálogo es el encuentro en que se solidarizan el reflexionar y el actuar de sus sujetos orientados hacia el mundo que debe ser transformado y humanizado, no puede reducirse a un mero depósito de ideas.', nota: '' },
      { texto: 'CAPÍTULO 4 — LA ANTIDIALOGICIDAD\n\nLa acción antidialógica es necesariamente dominadora y se divide en: conquista, dividir para oprimir, manipulación e invasión cultural.\n\nLa acción dialógica, en cambio, es: colaboración, unión, organización y síntesis cultural.\n\nConclusion de Freire: No hay palabra verdadera que no sea una unión inquebrantable entre acción y reflexión. No hay transformación sin nombrar el mundo. Y no hay nombre verdadero que no sea también acto de amor.\n\nEducar es un acto político. No hay educación neutral.', nota: '' },
    ],
    portada: _p('Pedagogía','del Oprimido','Paulo Freire','#7f1d1d','#fca5a5','▲'), creado: 'Clásico Educación', ultimaPag: 0, marcadores: [], palabras: 500, fuente: 'precargado'
  },

  {
    id: 'pre_edu_inclusiva',
    titulo: 'Educación Inclusiva — Marco Conceptual',
    autor: 'UNESCO',
    paginas: [
      { texto: 'EDUCACIÓN INCLUSIVA\nMarco Conceptual — UNESCO\n\n¿QUÉ ES LA EDUCACIÓN INCLUSIVA?\n\nLa educación inclusiva puede ser concebida como un proceso que permite abordar y responder a la diversidad de las necesidades de todos los educandos a través de una mayor participación en el aprendizaje, las actividades culturales y comunitarias, y reduciendo la exclusión dentro y fuera del sistema educativo.\n\nEl objetivo de la inclusión es brindar respuestas apropiadas al amplio espectro de necesidades de aprendizaje tanto en entornos formales como no formales de la educación.', nota: '' },
      { texto: 'PRINCIPIOS DE LA EDUCACIÓN INCLUSIVA\n\n1. La inclusión es un proceso: no se trata de fijar y lograr objetivos, sino de una búsqueda interminable de formas más adecuadas de responder a la diversidad.\n\n2. La inclusión busca la presencia, la participación y el éxito de todos los estudiantes. Presencia: dónde son educados. Participación: calidad de sus experiencias. Éxito: resultados de aprendizaje.\n\n3. La inclusión precisa la identificación y la eliminación de barreras. Las barreras pueden adoptar muchas formas: actitudes, información, prácticas institucionales y estructuras.\n\n4. La inclusión pone particular énfasis en grupos de alumnos en riesgo de marginación, exclusión o fracaso escolar.', nota: '' },
      { texto: 'BARRERAS PARA EL APRENDIZAJE Y LA PARTICIPACIÓN\n\nEl concepto de "barreras para el aprendizaje y la participación" fue desarrollado para contrastar con el de "necesidades educativas especiales". Las barreras surgen de la interacción entre los estudiantes y sus contextos: las personas, las políticas, las instituciones, las culturas y las circunstancias sociales y económicas.\n\nTipos de barreras:\n— Actitudinales: prejuicios, bajo nivel de expectativas.\n— Pedagógicas: metodologías poco flexibles, falta de adaptación.\n— Organizativas: distribución de recursos, horarios rígidos.\n— De acceso: barreras físicas, falta de materiales adecuados.', nota: '' },
      { texto: 'EL ROL DOCENTE EN LA INCLUSIÓN\n\nLos docentes son agentes clave del cambio en la construcción de escuelas inclusivas. Para asumir este rol necesitan:\n\n• Creer que todos los estudiantes pueden aprender.\n• Conocer estrategias de enseñanza diferenciada.\n• Trabajar colaborativamente con otros docentes, familias y profesionales.\n• Reflexionar continuamente sobre su práctica.\n• Adaptar los materiales curriculares a las necesidades del grupo.\n\nLa formación continua y el apoyo institucional son esenciales para que los docentes puedan responder efectivamente a la diversidad del aula.', nota: '' },
      { texto: 'DISEÑO UNIVERSAL PARA EL APRENDIZAJE (DUA)\n\nEl DUA es un marco que guía el diseño de metas, evaluaciones, métodos y materiales educativos flexibles que pueden ser personalizados y ajustados para las necesidades individuales.\n\nTres principios del DUA:\n1. Proporcionar múltiples medios de representación (el QUÉ del aprendizaje).\n2. Proporcionar múltiples medios de acción y expresión (el CÓMO del aprendizaje).\n3. Proporcionar múltiples medios de compromiso (el POR QUÉ del aprendizaje).\n\nEl DUA no es una receta sino un enfoque: diseñar desde el principio para la diversidad, no adaptar para unos pocos.', nota: '' },
      { texto: 'EVALUACIÓN INCLUSIVA\n\nLa evaluación en un marco inclusivo implica repensar qué evaluamos, cómo evaluamos y para qué evaluamos.\n\nUna evaluación inclusiva:\n— Evalúa el progreso de cada alumno respecto a sus propias posibilidades, no solo en relación a la norma del grupo.\n— Utiliza diversidad de instrumentos: observación, portafolios, autoevaluación, evaluación entre pares.\n— Tiene en cuenta el proceso, no solo el resultado final.\n— Es formativa: orienta la enseñanza y el aprendizaje, no solo certifica.\n\nLa evaluación inclusiva es una oportunidad para aprender, no solo para ser juzgado.', nota: '' },
    ],
    portada: _p('Educación','Inclusiva','UNESCO','#1565c0','#90caf9','♦'), creado: 'UNESCO', ultimaPag: 0, marcadores: [], palabras: 510, fuente: 'precargado'
  },

  {
    id: 'pre_edu_vigotsky',
    titulo: 'Pensamiento, lenguaje y aprendizaje — Vigotsky',
    autor: 'Lev Vigotsky',
    paginas: [
      { texto: 'PENSAMIENTO, LENGUAJE Y APRENDIZAJE\nLev Semionovich Vigotsky\n\nLA ZONA DE DESARROLLO PRÓXIMO\n\nVigotsky propuso que el aprendizaje ocurre en un espacio entre dos niveles de desarrollo:\n\n— Nivel de desarrollo real: lo que el niño puede hacer de manera independiente, resultado de ciclos de desarrollo ya completados.\n\n— Nivel de desarrollo potencial: lo que el niño puede hacer con ayuda de un adulto o un compañero más capaz.\n\nZona de Desarrollo Próximo (ZDP): la distancia entre estos dos niveles. Es el espacio donde ocurre el aprendizaje significativo.', nota: '' },
      { texto: 'EL ROL DEL LENGUAJE EN EL PENSAMIENTO\n\nPara Vigotsky, el lenguaje y el pensamiento tienen raíces distintas pero se entrelazan durante el desarrollo.\n\nEl habla privada (cuando el niño habla consigo mismo mientras resuelve un problema) no es conducta egocéntrica sin sentido, sino una herramienta de pensamiento.\n\nEl lenguaje primero cumple una función comunicativa y social; luego se interioriza y se convierte en pensamiento verbal.\n\n"En el desarrollo cultural del niño, toda función aparece dos veces: primero entre personas —interpsicológica— y luego en el interior del propio niño —intrapsicológica."', nota: '' },
      { texto: 'EL ANDAMIAJE\n\nEl concepto de andamiaje (scaffolding) fue desarrollado por Jerome Bruner a partir de las ideas de Vigotsky.\n\nEl andamiaje es el apoyo temporario que proporciona el maestro, el padre o un compañero más capaz para que el alumno pueda realizar una tarea que todavía no puede hacer solo.\n\nCaracterísticas del buen andamiaje:\n— Es ajustado a las necesidades del alumno.\n— Es temporario: se retira cuando el alumno puede hacerlo solo.\n— Es sensible al proceso: sigue el ritmo del alumno.\n— Transfiere el control gradualmente al alumno.', nota: '' },
      { texto: 'APRENDIZAJE COLABORATIVO\n\nDe las ideas de Vigotsky surge la importancia del aprendizaje colaborativo: trabajar en grupos donde los estudiantes se ayudan mutuamente.\n\nEn el trabajo en grupos, cada alumno puede ser "más capaz" para otro en alguna tarea. El que explica también aprende: consolidar el conocimiento para enseñarlo es una de las formas más efectivas de aprender.\n\nEstrategias:\n— Tutoría entre pares.\n— Trabajo en grupos heterogéneos.\n— Proyectos colaborativos.\n— Aprendizaje cooperativo estructurado.', nota: '' },
      { texto: 'IMPLICANCIAS PEDAGÓGICAS\n\nLas ideas de Vigotsky tienen consecuencias profundas para la enseñanza:\n\n• El docente debe conocer la ZDP de cada alumno para proponer desafíos que estén un poco más allá de lo que puede hacer solo: ni demasiado fácil (aburre) ni demasiado difícil (frustra).\n\n• La evaluación debe mostrar no solo lo que el alumno ya sabe, sino lo que está en proceso de aprender.\n\n• El contexto social y cultural no es un telón de fondo del aprendizaje: es parte constitutiva del mismo.\n\n• La interacción entre pares es una fuente poderosa de aprendizaje.', nota: '' },
      { texto: 'VIGOTSKY Y LA EDUCACIÓN ESPECIAL\n\nVigotsky fue uno de los primeros en estudiar el desarrollo de niños con discapacidades desde una perspectiva no deficitaria.\n\nSu idea central: la discapacidad no determina el destino de un niño. Lo que importa es el camino que se le ofrece para el desarrollo.\n\n"El niño con discapacidad no es simplemente un niño menos desarrollado: es un niño que se ha desarrollado de otra manera."\n\nEsto fue revolucionario en su época y sigue siendo la base de la educación inclusiva actual: partir de las capacidades, no de las limitaciones.', nota: '' },
    ],
    portada: _p('Pensamiento y','Lenguaje','Lev Vigotsky','#4a148c','#ce93d8','△'), creado: 'Psicología Educacional', ultimaPag: 0, marcadores: [], palabras: 520, fuente: 'precargado'
  },

  {
    id: 'pre_edu_piaget',
    titulo: 'Desarrollo cognitivo — Piaget',
    autor: 'Jean Piaget',
    paginas: [
      { texto: 'EL DESARROLLO COGNITIVO\nBases del pensamiento de Jean Piaget\n\nPIAGET Y EL CONSTRUCTIVISMO\n\nJean Piaget (1896-1980) fue el principal teórico del desarrollo cognitivo. Su teoría propone que el conocimiento no es una copia de la realidad, sino una construcción activa del sujeto.\n\nDos procesos fundamentales:\n— Asimilación: incorporar nueva información a los esquemas existentes.\n— Acomodación: modificar los esquemas existentes para incorporar información que no encaja.\n— Equilibración: el proceso que regula el balance entre asimilación y acomodación.', nota: '' },
      { texto: 'LAS CUATRO ETAPAS DEL DESARROLLO\n\n1. SENSORIOMOTORA (0 a 2 años): el niño conoce el mundo a través de los sentidos y la acción motora. Logro clave: la permanencia del objeto.\n\n2. PREOPERACIONAL (2 a 7 años): aparece el lenguaje y el pensamiento simbólico. Características: egocentrismo, animismo, pensamiento mágico.\n\n3. OPERACIONES CONCRETAS (7 a 12 años): el niño puede realizar operaciones lógicas pero sobre objetos concretos. Logros: conservación, seriación, clasificación.\n\n4. OPERACIONES FORMALES (12 años en adelante): aparece el pensamiento abstracto y la capacidad de razonar sobre hipótesis.', nota: '' },
      { texto: 'IMPLICANCIAS PARA LA ENSEÑANZA\n\nSi el conocimiento se construye activamente, entonces:\n\n— No alcanza con explicar: hay que crear situaciones donde el alumno pueda explorar, manipular, descubrir.\n\n— Cada etapa tiene sus propias posibilidades y limitaciones. No se puede "saltar" etapas: hay que respetar el momento evolutivo.\n\n— El error es parte del aprendizaje: un alumno que se equivoca está construyendo su comprensión.\n\n— El conflicto cognitivo (enfrentarse a algo que no encaja en los esquemas existentes) es el motor del aprendizaje.', nota: '' },
      { texto: 'EL ROL DEL DOCENTE SEGÚN PIAGET\n\nPara Piaget, el docente no debe ser un transmisor de conocimientos sino un facilitador del desarrollo.\n\n"El objetivo principal de la educación es crear hombres capaces de hacer cosas nuevas, no simplemente de repetir lo que otras generaciones han hecho."\n\nEl docente piagetiano:\n— Crea ambientes ricos en materiales y situaciones para explorar.\n— Formula preguntas que generan conflicto cognitivo.\n— Deja tiempo para que el alumno elabore sus propias conclusiones.\n— Evalúa el proceso de razonamiento, no solo el resultado.', nota: '' },
      { texto: 'CRÍTICAS Y ACTUALIZACIONES\n\nLa teoría de Piaget ha sido muy influyente pero también ha recibido críticas:\n\n— Subestimó las capacidades de los niños pequeños.\n— Las etapas no son tan rígidas ni universales como propuso.\n— No consideró suficientemente el rol de la cultura y el contexto social (aquí es donde Vigotsky completa a Piaget).\n\nLa síntesis actual: el desarrollo cognitivo es a la vez un proceso interno de construcción (Piaget) y un proceso social y cultural (Vigotsky). Ambas perspectivas son necesarias para comprender cómo aprenden los niños.', nota: '' },
    ],
    portada: _p('Desarrollo','Cognitivo','Jean Piaget','#c2410c','#ffb74d','●'), creado: 'Psicología Educacional', ultimaPag: 0, marcadores: [], palabras: 480, fuente: 'precargado'
  },

  {
    id: 'pre_edu_gardner',
    titulo: 'Inteligencias Múltiples — Gardner',
    autor: 'Howard Gardner',
    paginas: [
      { texto: 'INTELIGENCIAS MÚLTIPLES\nBasado en la teoría de Howard Gardner\n\n¿QUÉ ES LA INTELIGENCIA?\n\nTradicionalmente, la inteligencia se midió con un número: el cociente intelectual (CI). Este número reflejaba básicamente habilidades lingüísticas y lógico-matemáticas.\n\nHoward Gardner propuso en 1983, en su libro "Estructuras de la mente", que la inteligencia no es una sola capacidad, sino un conjunto de capacidades relativamente independientes entre sí.\n\nSu definición de inteligencia: "la capacidad de resolver problemas o crear productos que son valorados en uno o más contextos culturales."', nota: '' },
      { texto: 'LAS OCHO INTELIGENCIAS\n\n1. LINGÜÍSTICA: habilidad para usar el lenguaje de manera efectiva, oral y escrita.\n\n2. LÓGICO-MATEMÁTICA: capacidad para el razonamiento lógico, los números y el pensamiento científico.\n\n3. ESPACIAL: habilidad para percibir y transformar el mundo visual-espacial. Arquitectos, artistas, navegantes.\n\n4. MUSICAL: sensibilidad al ritmo, la melodía, el tono y la forma musical.\n\n5. CORPORAL-KINESTÉSICA: habilidad para usar el cuerpo con precisión. Deportistas, bailarines, cirujanos.', nota: '' },
      { texto: 'LAS OCHO INTELIGENCIAS (continuación)\n\n6. INTERPERSONAL: capacidad para entender las intenciones, motivaciones y deseos de otras personas. Líderes, docentes, vendedores.\n\n7. INTRAPERSONAL: capacidad para conocerse a uno mismo: las propias emociones, metas, fortalezas y debilidades.\n\n8. NATURALISTA: habilidad para reconocer y clasificar elementos del ambiente natural. Biólogos, agricultores, cocineros.\n\nGardner también consideró la inteligencia existencial (la capacidad de plantearse preguntas sobre la existencia humana).', nota: '' },
      { texto: 'IMPLICANCIAS PARA EL AULA\n\nSi hay múltiples tipos de inteligencia, entonces:\n\n— No existe "el alumno inteligente" y "el alumno que no puede". Existen alumnos con distintos perfiles de inteligencia.\n\n— Un alumno que fracasa en lengua y matemática puede tener una inteligencia musical o corporal muy desarrollada.\n\n— La escuela tradicional valora casi exclusivamente las inteligencias lingüística y lógico-matemática. Una escuela que valore la diversidad aprovecha todos los talentos.\n\n— La enseñanza puede enriquecerse presentando los contenidos de múltiples maneras: con movimiento, música, imágenes, debates.', nota: '' },
      { texto: 'CÓMO APLICARLO EN EL AULA\n\nEstrategias prácticas:\n\n• Observar a los alumnos en distintas actividades para identificar sus puntos fuertes.\n• Diseñar actividades variadas que permitan a distintos tipos de inteligencia brillar.\n• Evaluar de maneras diversas: no solo prueba escrita, también exposición oral, proyecto, producción artística.\n• Usar la inteligencia fuerte de un alumno como puerta de entrada para trabajar áreas más débiles.\n• Crear momentos de trabajo en equipo donde distintos talentos se complementen.\n\nLa teoría de las inteligencias múltiples no es una receta sino una invitación a ver a cada alumno como un ser complejo y múltiple.', nota: '' },
    ],
    portada: _p('Inteligencias','Múltiples','Howard Gardner','#1b5e20','#81c784','★'), creado: 'Psicología Educacional', ultimaPag: 0, marcadores: [], palabras: 470, fuente: 'precargado'
  },

  {
    id: 'pre_edu_ausubel',
    titulo: 'Aprendizaje Significativo — Ausubel',
    autor: 'David Ausubel',
    paginas: [
      { texto: 'APRENDIZAJE SIGNIFICATIVO\nBases del pensamiento de David Ausubel\n\n¿QUÉ ES EL APRENDIZAJE SIGNIFICATIVO?\n\nDavid Ausubel propuso que el aprendizaje más duradero y útil es el que se conecta con lo que el alumno ya sabe. A esta conexión la llamó aprendizaje significativo.\n\nSu frase clave: "Si tuviese que reducir toda la psicología educativa a un solo principio, diría lo siguiente: el factor que más influye en el aprendizaje es lo que el alumno ya sabe. Averígüese esto y enséñese en consecuencia."', nota: '' },
      { texto: 'APRENDIZAJE SIGNIFICATIVO VS. APRENDIZAJE MEMORÍSTICO\n\nAprendizaje memorístico (o mecánico):\n— El alumno memoriza sin comprender.\n— La información se almacena de manera aislada.\n— Se olvida rápidamente.\n— No puede transferirse a situaciones nuevas.\n\nAprendizaje significativo:\n— El alumno relaciona la nueva información con lo que ya sabe.\n— La información se integra en la estructura cognitiva existente.\n— Es durable y resistente al olvido.\n— Puede transferirse y aplicarse en contextos nuevos.', nota: '' },
      { texto: 'CONDICIONES PARA EL APRENDIZAJE SIGNIFICATIVO\n\nPara que ocurra el aprendizaje significativo se necesitan dos condiciones:\n\n1. El material debe ser potencialmente significativo:\n— Lógicamente significativo: el contenido tiene coherencia interna.\n— Psicológicamente significativo: el alumno tiene en su estructura cognitiva los conocimientos previos necesarios para relacionarlo.\n\n2. El alumno debe tener disposición para aprender significativamente: no memorizar mecánicamente sino conectar con lo que ya sabe.\n\nSi falta alguna de estas condiciones, el aprendizaje será mecánico.', nota: '' },
      { texto: 'LOS ORGANIZADORES PREVIOS\n\nAusubel propuso el uso de "organizadores previos": materiales introductorios que se presentan antes del contenido y que ayudan al alumno a activar o construir los conocimientos previos necesarios.\n\nTipos de organizadores previos:\n— Expositivos: cuando el alumno no tiene conocimientos previos relacionados. Introducen conceptos nuevos de manera general antes de los detalles.\n— Comparativos: cuando el alumno sí tiene conocimientos previos. Establecen semejanzas y diferencias entre lo nuevo y lo conocido.\n\nEl mapa conceptual es una herramienta que puede funcionar como organizador previo y también como instrumento de evaluación.', nota: '' },
      { texto: 'IMPLICANCIAS PARA LA ENSEÑANZA\n\nLa teoría de Ausubel sugiere que:\n\n1. Antes de enseñar algo nuevo, hay que explorar qué saben los alumnos sobre ese tema. Las ideas previas —aunque incorrectas— son el punto de partida del aprendizaje.\n\n2. Hay que presentar el contenido de manera organizada y relacionada, no como datos sueltos.\n\n3. Los ejemplos son fundamentales: conectan el concepto abstracto con experiencias concretas del alumno.\n\n4. La evaluación debe verificar si el alumno comprendió y puede relacionar, no solo si memorizó.\n\n5. El repaso debe ser espaciado y con variación: volver a los contenidos en distintos contextos consolida el aprendizaje significativo.', nota: '' },
    ],
    portada: _p('Aprendizaje','Significativo','David Ausubel','#006064','#4dd0e1','◇'), creado: 'Psicología Educacional', ultimaPag: 0, marcadores: [], palabras: 490, fuente: 'precargado'
  },

  {
    id: 'pre_edu_atencion_diversidad',
    titulo: 'Atención a la Diversidad en el Aula',
    autor: 'Recursos educativos UNESCO/OEI',
    paginas: [
      { texto: 'ATENCIÓN A LA DIVERSIDAD EN EL AULA\n\n¿QUÉ SIGNIFICA ATENDER LA DIVERSIDAD?\n\nAtender la diversidad en el aula significa reconocer que cada alumno es único —en su historia, sus capacidades, sus ritmos, sus intereses y sus contextos— y diseñar la enseñanza de manera que todos puedan aprender.\n\nLa diversidad no es un problema a resolver sino una realidad a gestionar como oportunidad. Un aula diversa, bien gestionada, enriquece el aprendizaje de todos sus integrantes.', nota: '' },
      { texto: 'TIPOS DE DIVERSIDAD EN EL AULA\n\n— Diversidad cognitiva: distintos ritmos y estilos de aprendizaje, diferentes inteligencias predominantes.\n\n— Diversidad cultural y lingüística: alumnos de distintas culturas, familias migrantes, distintas lenguas maternas.\n\n— Diversidad socioeconómica: diferentes contextos familiares y recursos disponibles en el hogar.\n\n— Diversidad por necesidades educativas especiales: alumnos con discapacidades físicas, sensoriales, cognitivas o socioemocionales.\n\n— Diversidad de género e identidad: distintas formas de identificación y expresión de género.\n\nTodas estas diversidades coexisten en cualquier aula.', nota: '' },
      { texto: 'ESTRATEGIAS DE ENSEÑANZA DIFERENCIADA\n\nLa enseñanza diferenciada implica adaptar el contenido, el proceso y/o el producto según las necesidades de los alumnos.\n\nEstrategias prácticas:\n• Proponer actividades con distintos niveles de complejidad.\n• Ofrecer opciones para demostrar lo aprendido (oral, escrito, visual, corporal).\n• Usar agrupamientos flexibles: a veces grupos por nivel, otras por interés, otras heterogéneos.\n• Dar más tiempo a quienes lo necesitan.\n• Proporcionar apoyos visuales, esquemas y organizadores gráficos.\n• Usar la tecnología como herramienta de accesibilidad.', nota: '' },
      { texto: 'ADAPTACIONES CURRICULARES\n\nUna adaptación curricular es la modificación de uno o más elementos del currículo (objetivos, contenidos, metodología, evaluación) para responder a las necesidades de un alumno.\n\nTipos:\n— No significativas: modificaciones menores que no alteran los objetivos básicos. Más tiempo, materiales distintos, lugar preferencial en el aula.\n\n— Significativas: modifican objetivos básicos. Se aplican cuando las no significativas son insuficientes. Requieren acuerdo entre docentes, directivos y familia.\n\nPrincipio fundamental: la adaptación debe ser individualizada y revisada periódicamente.', nota: '' },
      { texto: 'EL TRABAJO CON FAMILIAS\n\nLa atención a la diversidad requiere el trabajo conjunto entre escuela y familia.\n\nBuenas prácticas:\n• Entrevistas periódicas para compartir observaciones y acordar estrategias.\n• Comunicación clara y respetuosa, evitando el lenguaje técnico que excluye.\n• Involucrar a la familia en la elaboración de las adaptaciones.\n• Informar regularmente sobre los progresos, no solo sobre las dificultades.\n• Reconocer que la familia conoce a su hijo de maneras que la escuela no puede.\n\nLa familia y la escuela son aliadas, no adversarias. Cuando trabajan juntas, el alumno gana.', nota: '' },
      { texto: 'EVALUACIÓN EN CONTEXTOS DIVERSOS\n\nUna evaluación que atiende la diversidad:\n\n— Evalúa el progreso de cada alumno respecto a sus propias posibilidades.\n— Usa múltiples instrumentos y formatos.\n— Incluye instancias de autoevaluación y coevaluación.\n— Se realiza en distintos momentos (diagnóstica, formativa, sumativa).\n— Tiene en cuenta el contexto del alumno.\n\nLa calificación no es el único objetivo de la evaluación. La evaluación bien entendida es una conversación entre docente y alumno sobre el aprendizaje: qué se logró, qué falta, cómo seguir.', nota: '' },
    ],
    portada: _p('Atención a la','Diversidad','UNESCO / OEI','#880e4f','#f48fb1','●'), creado: 'Recursos Educativos', ultimaPag: 0, marcadores: [], palabras: 520, fuente: 'precargado'
  },

  {
    id: 'pre_edu_convivencia',
    titulo: 'Convivencia Escolar y Resolución de Conflictos',
    autor: 'Recursos educativos UNESCO/OEI',
    paginas: [
      { texto: 'CONVIVENCIA ESCOLAR Y RESOLUCIÓN DE CONFLICTOS\n\n¿QUÉ ES LA CONVIVENCIA ESCOLAR?\n\nLa convivencia escolar es el conjunto de relaciones que se establecen entre todos los miembros de la comunidad educativa: alumnos, docentes, directivos, familias y personal no docente.\n\nUna buena convivencia no es la ausencia de conflictos —que son inevitables— sino la capacidad de la comunidad para gestionarlos de manera constructiva, respetando los derechos de todos.', nota: '' },
      { texto: 'EL CONFLICTO EN LA ESCUELA\n\nEl conflicto es parte natural de la vida en comunidad. Su presencia no indica que algo está mal: indica que distintas personas tienen distintas necesidades, intereses o perspectivas.\n\nEl conflicto es una oportunidad de aprendizaje cuando:\n— Se aborda de manera dialogada y respetuosa.\n— Se buscan soluciones que contemplen las necesidades de todas las partes.\n— Se reflexiona sobre lo ocurrido para prevenir situaciones similares.\n\nEl conflicto se vuelve problemático cuando se resuelve con violencia —física, verbal o simbólica— o cuando no se resuelve y se cronifica.', nota: '' },
      { texto: 'MEDIACIÓN ESCOLAR\n\nLa mediación es un proceso en el que un tercero neutral (el mediador) ayuda a las partes en conflicto a comunicarse y encontrar una solución mutuamente aceptable.\n\nCaracterísticas:\n— Voluntaria: las partes eligen participar.\n— Confidencial: lo que se dice en mediación no sale de ese espacio.\n— Neutral: el mediador no toma partido.\n— Colaborativa: busca que ambas partes ganen, no que una gane y la otra pierda.\n\nLa mediación entre pares —donde los propios alumnos son mediadores— es una herramienta especialmente poderosa porque fortalece habilidades socioemocionales y empodera a los estudiantes.', nota: '' },
      { texto: 'CONSTRUCCIÓN DE NORMAS EN EL AULA\n\nLas normas construidas colectivamente tienen más legitimidad que las impuestas. Cuando los alumnos participan en la elaboración de las reglas del aula, las comprenden mejor y las respetan más.\n\nProceso de construcción colectiva de normas:\n1. Reflexionar juntos sobre qué necesitamos para trabajar bien.\n2. Proponer normas entre todos.\n3. Debatirlas y acordarlas.\n4. Escribirlas y exponerlas en el aula.\n5. Revisarlas periódicamente.\n\nLas normas deben ser pocas, claras, positivas (decir qué hacer, no solo qué no hacer) y concretas.', nota: '' },
      { texto: 'VIOLENCIA ESCOLAR: PREVENCIÓN Y RESPUESTA\n\nLa violencia escolar incluye:\n— Agresión física, verbal o psicológica entre pares.\n— Acoso escolar (bullying): agresión sistemática con desequilibrio de poder.\n— Ciberbullying: acoso a través de medios digitales.\n— Violencia de adultos hacia alumnos.\n\nPrevención:\n• Construir un clima escolar de respeto y pertenencia.\n• Trabajar explícitamente las habilidades socioemocionales.\n• Establecer protocolos claros de intervención.\n• Involucrar a las familias.\n\nRespuesta: ante situaciones de violencia, actuar rápido, escuchar a todas las partes y proteger a quien fue dañado.', nota: '' },
      { texto: 'HABILIDADES SOCIOEMOCIONALES\n\nLas habilidades socioemocionales son capacidades que permiten a las personas relacionarse de manera efectiva, gestionar sus emociones y tomar decisiones responsables.\n\nHabilidades clave:\n— Autoconciencia: conocer las propias emociones y pensamientos.\n— Autogestión: regular las emociones y el comportamiento.\n— Conciencia social: empatizar con los demás, comprender perspectivas diferentes.\n— Habilidades relacionales: comunicarse, cooperar, resolver conflictos.\n— Toma de decisiones responsable.\n\nEstas habilidades se enseñan y se aprenden. La escuela es un lugar privilegiado para desarrollarlas, especialmente cuando los docentes las modelan en su propio comportamiento.', nota: '' },
    ],
    portada: _p('Convivencia','Escolar','UNESCO / OEI','#33691e','#aed581','♡'), creado: 'Recursos Educativos', ultimaPag: 0, marcadores: [], palabras: 530, fuente: 'precargado'
  },

  {
    id: 'pre_edu_familias',
    titulo: 'Familias y Escuelas — Trabajo Conjunto',
    autor: 'Recursos educativos UNESCO/OEI',
    paginas: [
      { texto: 'FAMILIAS Y ESCUELAS — TRABAJO CONJUNTO\n\nLA IMPORTANCIA DE LA ALIANZA FAMILIA-ESCUELA\n\nLa investigación educativa es clara: cuando las familias se involucran en la educación de sus hijos, los resultados mejoran. No solo en lo académico, sino también en la motivación, la asistencia y el bienestar emocional de los alumnos.\n\nSin embargo, construir esta alianza no es automático. Requiere esfuerzo, habilidades comunicativas y, sobre todo, una actitud de respeto mutuo entre docentes y familias.', nota: '' },
      { texto: 'TIPOS DE PARTICIPACIÓN FAMILIAR\n\nJoyce Epstein identificó seis tipos de participación familiar:\n\n1. Crianza: apoyar a las familias en su rol de padres.\n2. Comunicación: intercambio efectivo entre escuela y familia.\n3. Voluntariado: familias que apoyan actividades escolares.\n4. Aprendizaje en casa: orientar a las familias sobre cómo apoyar el aprendizaje.\n5. Toma de decisiones: incluir a las familias en las decisiones de la escuela.\n6. Colaboración con la comunidad: vincular la escuela con recursos del entorno.\n\nCada tipo requiere estrategias específicas por parte de la escuela.', nota: '' },
      { texto: 'COMUNICACIÓN EFECTIVA CON LAS FAMILIAS\n\nPrincipios para una comunicación efectiva:\n\n— Ser proactivo: no esperar el problema para comunicarse. Compartir también los logros y avances.\n— Ser claro: usar lenguaje accesible, sin jerga técnica.\n— Ser respetuoso: tratar a las familias como aliadas, no como subordinadas.\n— Escuchar activamente: la reunión con la familia es una conversación, no un informe unilateral.\n— Ser específico: hablar de conductas y situaciones concretas, no de etiquetas generales.\n\nLa primera comunicación con una familia no debería ser para reportar un problema.', nota: '' },
      { texto: 'FAMILIAS EN SITUACIÓN DE VULNERABILIDAD\n\nAlgunas familias tienen mayores dificultades para involucrarse en la escuela:\n— Familias con trabajo en horario escolar o múltiples empleos.\n— Familias con experiencias propias negativas en la escuela.\n— Familias de contextos migrantes o culturalmente diferentes.\n— Familias en situación de crisis (económica, de salud, violencia doméstica).\n\nLa escuela puede:\n• Ofrecer distintos horarios y modalidades de reunión.\n• Ir al encuentro de las familias (visitas domiciliarias).\n• Evitar el lenguaje que culpabiliza.\n• Reconocer el esfuerzo de cada familia, cualquiera sea su situación.', nota: '' },
      { texto: 'EL DOCENTE COMO PUENTE\n\nEl docente ocupa una posición privilegiada para tender puentes entre la escuela y las familias.\n\nPara construir esa relación:\n• Conocer las historias familiares de sus alumnos (con discreción).\n• Valorar el capital cultural de cada familia, aunque sea diferente al escolar.\n• Compartir lo que observa en el aula de manera empática y constructiva.\n• Involucrar a las familias en actividades significativas del aula.\n• Ser el referente al que la familia puede recurrir con confianza.\n\nUna familia que confía en el docente de su hijo es un aliado poderoso para el aprendizaje.', nota: '' },
    ],
    portada: _p('Familias','y Escuelas','UNESCO / OEI','#bf360c','#ff8a65','◆'), creado: 'Recursos Educativos', ultimaPag: 0, marcadores: [], palabras: 480, fuente: 'precargado'
  },

  // ── LITERATURA ARGENTINA ───────────────────────────────────────────────────

  {
    id: 'pre_quijote',
    titulo: 'Don Quijote de la Mancha',
    autor: 'Miguel de Cervantes',
    paginas: [
      { texto: 'DON QUIJOTE DE LA MANCHA\nMiguel de Cervantes — 1605\n\nCAPÍTULO PRIMERO\nQue trata de la condición y ejercicio del famoso hidalgo Don Quijote de la Mancha\n\nEn un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor.\n\nUna olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.', nota: '' },
      { texto: 'Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro; gran madrugador y amigo de la caza.\n\nQuieren decir que tenía el sobrenombre de Quijada o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosímiles se deja entender que se llamaba Quijana.', nota: '' },
      { texto: 'Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso —que eran los más del año— se daba a leer libros de caballerías con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza y aun la administración de su hacienda.\n\nEn resolución, él se enfrascó tanto en su lectura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer, se le secó el cerebro de manera que vino a perder el juicio.', nota: '' },
    ],
    portada: _p('Don Quijote','de la Mancha','Miguel de Cervantes','#4e342e','#d7ccc8','◆'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 280, fuente: 'precargado'
  },

  {
    id: 'pre_fierro',
    titulo: 'Martín Fierro',
    autor: 'José Hernández',
    paginas: [
      { texto: 'MARTÍN FIERRO\nJosé Hernández — 1872\n\nAquí me pongo a cantar\nal compás de la vigüela,\nque el hombre que lo desvela\nuna pena estraordinaria,\ncomo la ave solitaria\ncon el cantar se consuela.\n\nPido a los Santos del Cielo\nque ayuden mi pensamiento;\nles pido en este momento\nque voy a cantar mi historia\nme refresquen la memoria\ny aclaren mi entendimiento.', nota: '' },
      { texto: 'Vengan santos milagrosos,\nvengan todos en mi ayuda,\nque la lengua se me añuda\ny se me turba la vista;\npido a mi Dios que me asista\nen una ocasión tan ruda.\n\nMas ande otro criollo pasa\nMartín Fierro ha de pasar;\nnada lo hace recular\nni las fantasmas lo espantan;\ny dende que todos cantan\nyo también quiero cantar.\n\nCantando me he de morir,\ncantando me han de enterrar,\ny cantando he de llegar\nal pie del Eterno Padre.', nota: '' },
      { texto: 'Soy gaucho, y entiendaló\ncomo mi lengua lo explica:\npara mí la tierra es chica\ny pudiera ser mayor;\nni la víbora me pica\nni quema mi frente el sol.\n\nNací como nace el peje\nen el fondo de la mar;\nnaides me puede quitar\naquello que Dios me dio:\nlo que al mundo truje yo\ndel mundo lo he de llevar.\n\nMi gloria es vivir tan libre\ncomo el pájaro del cielo;\nno hago nido en este suelo\nande hay tanto que sufrir;\ny naides me ha de seguir\ncuando yo remuento el vuelo.', nota: '' },
    ],
    portada: _p('Martín Fierro','','José Hernández','#92400e','#fcd34d','◆'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 220, fuente: 'precargado'
  },

  {
    id: 'pre_facundo',
    titulo: 'Facundo — Civilización y Barbarie',
    autor: 'Domingo F. Sarmiento',
    paginas: [
      { texto: 'FACUNDO\nCivilización y Barbarie\nDomingo Faustino Sarmiento — 1845\n\nCAPÍTULO I — ASPECTO FÍSICO DE LA REPÚBLICA ARGENTINA\n\nEl continente americano termina al sur en una punta, en cuya extremidad se forma el estrecho de Magallanes. Al oeste y a corta distancia de los Andes, el mar Pacífico; al este, el Atlántico. La pampa extiéndese al norte por espacio de dos mil leguas.\n\nLa extensión de las pampas, ese mar de tierra que no tiene fin conocido, esa llanura sin accidentes, esa uniformidad que cansa la vista, esa soledad sin límites, es sin duda alguna lo que da a la vida del argentino su carácter peculiar.', nota: '' },
      { texto: 'El hombre de la ciudad viste el traje europeo, vive de la vida civilizada tal como la conocemos en todas partes. Saliendo del recinto de la ciudad, todo cambia de aspecto: el hombre de campo lleva otro traje, que llamaré americano; sus hábitos de vida son diferentes; sus necesidades, peculiares y limitadas; parecen dos sociedades distintas, dos pueblos extraños uno al otro.\n\nEsta dicotomía —ciudad y campo, civilización y barbarie— es el eje sobre el que gira toda la historia argentina del siglo XIX, según Sarmiento.', nota: '' },
      { texto: 'EL GAUCHO\n\nEl gaucho es el producto natural de la pampa. Vive en ella, la conoce como nadie, se mueve en ella con la libertad y la gracia del que habita su propio elemento.\n\nPero esa libertad que el gaucho encarna, esa desconfianza de la ley y la ciudad, esa violencia que brota cuando se siente amenazado, son también —dice Sarmiento— las fuerzas que impiden el progreso.\n\nFacundo Quiroga es, para Sarmiento, la encarnación de esa barbarie: un caudillo surgido de la pampa que resume todas las contradicciones de la Argentina de su tiempo.', nota: '' },
    ],
    portada: _p('Facundo','Civil. y Barbarie','D. F. Sarmiento','#78350f','#d6d3d1','⊕'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 280, fuente: 'precargado'
  },

  {
    id: 'pre_matadero',
    titulo: 'El Matadero',
    autor: 'Esteban Echeverría',
    paginas: [
      { texto: 'EL MATADERO\nEsteban Echeverría — escrito ~1838, publicado 1871\n\nA pesar de que la mía es historia, no la empezaré por el arca de Noé y la genealogía de sus ascendientes como acostumbraban hacerlo los antiguos historiadores españoles de América.\n\nLos sucesos de mi narración pasaban por los años de Cristo de 183... Estábamos a más en el período cuaresmal en que la Iglesia Católica reprueba la sangre impura. Y como la Iglesia tiene el poder de adoptar providencias preventivas contra las tentaciones de la carne, el resultado de esta medida es que la gente se hace más hambrienta.', nota: '' },
      { texto: 'El Matadero de la Convalecencia o del Alto, sito en las quintas al sur de la ciudad, es una gran playa en forma rectangular. Esta playa, con declive al sur, está cortada por un zanjón labrado por la corriente de las aguas pluviales, en cuyos bordes laterales se muestran innumerables cuevas de ratones.\n\nEra el Matadero de Buenos Aires el lugar donde, durante el gobierno de Rosas, se concentraba lo más brutal y violento del orden social. Echeverría lo convierte en metáfora del régimen: un espacio donde la barbarie política se exhibe sin disimulo.', nota: '' },
      { texto: 'El cuento termina con la muerte del joven unitario que se niega a humillarse ante los federales del matadero. Su muerte es la del que prefiere morir libre antes que vivir sometido.\n\n"Primero degollarme que desnudarme, infame canalla."\n\nEcheverría escribió El Matadero en secreto, bajo la persecución de Rosas. No pudo publicarlo en vida. Es el primer cuento argentino y uno de los textos fundacionales de la literatura latinoamericana. En él conviven el realismo crudo y la denuncia política.', nota: '' },
    ],
    portada: _p('El Matadero','','Esteban Echeverría','#1c1c1c','#d4d4d8','■'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 280, fuente: 'precargado'
  },

  {
    id: 'pre_amalia',
    titulo: 'Amalia',
    autor: 'José Mármol',
    paginas: [
      { texto: 'AMALIA\nJosé Mármol — 1851\n\nPRIMERA NOVELA ARGENTINA\n\nLa novela se desarrolla en Buenos Aires en mayo de 1840, durante el régimen de Juan Manuel de Rosas y el terror de la Mazorca —la organización parapolicial del rosismo.\n\nEduardo Belgrano, sobrino del prócer Manuel Belgrano, intenta huir de Buenos Aires con un grupo de unitarios. Son sorprendidos por la Mazorca. Eduardo resulta herido y es rescatado por su amigo Daniel Bello, quien lo lleva a la casa de su prima Amalia, una joven viuda de Tucumán que vive en las afueras de la ciudad.', nota: '' },
      { texto: 'La casa de Amalia se convierte en un refugio frente al terror rosista. Allí, Eduardo y Amalia se enamoran mientras afuera el régimen aprieta sus garras sobre Buenos Aires.\n\nMármol construye una novela de amor, acción y denuncia política. Amalia es, a la vez, una historia de amor romántico y un documento histórico sobre la época de Rosas. El autor escribía por entregas en el periódico La Semana, en Montevideo, exiliado como tantos intelectuales argentinos de la época.\n\nLa obra es fundacional en la literatura argentina: establece los géneros del romanticismo y la novela política que marcarán la literatura del siglo XIX.', nota: '' },
      { texto: 'DANIEL BELLO Y AMALIA\n\nDaniel Bello es el personaje más complejo de la novela: un hombre que simula adherir al rosismo para sobrevivir y proteger a sus amigos unitarios, moviéndose en las sombras de la sociedad porteña.\n\nAmalia, en cambio, es la heroína romántica: valiente, leal, capaz de arriesgar su vida por amor y por principios.\n\nLa novela termina trágicamente, como corresponde al romanticismo: el amor no puede sobrevivir al terror político. Eduardo y Amalia son asesinados por la Mazorca en la noche de su boda.\n\nAmalia es una declaración de que no hay vida privada posible bajo la tiranía.', nota: '' },
    ],
    portada: _p('Amalia','','José Mármol','#6a1b9a','#ce93d8','♡'), creado: 'Clásico Argentino', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_quiroga',
    titulo: 'Cuentos de la Selva',
    autor: 'Horacio Quiroga',
    paginas: [
      { texto: 'CUENTOS DE LA SELVA\nHoracio Quiroga — 1918\n\nLA TORTUGA GIGANTE\n\nHabía una vez un hombre que vivía en Buenos Aires y estaba muy enfermo. Vivía solo y no tenía familia. Los médicos le dijeron que debía ir a vivir al campo para curarse.\n\nEl hombre se fue al monte. Cazaba y pescaba para comer. Poco a poco fue mejorando. Un día encontró una tortuga gigante que también estaba muy enferma y casi muerta de hambre.', nota: '' },
      { texto: 'El hombre la curó y le dio de comer durante varios días. La tortuga sanó y los dos se hicieron amigos.\n\nPero el hombre también se enfermó de nuevo, esta vez gravemente. No podía moverse. Estaba solo en el monte, lejos de todo.\n\nEntonces la tortuga lo cargó en su caparazón y caminó durante días y días por el monte, sin detenerse, hasta llegar a Buenos Aires. Allí los médicos atendieron al hombre y se salvó.\n\nLa tortuga esperó en la vereda hasta que el hombre se curó. Cuando salió del hospital, el hombre abrazó a la tortuga y le dijo: "Gracias, amiga. Volvamos juntos al monte."', nota: '' },
      { texto: 'LA ABEJA HARAGANA\n\nHabía una vez en una colmena una abeja que no quería trabajar. Mientras las otras abejas salían temprano a buscar miel, ella se quedaba durmiendo.\n\nUn día la reina la llamó y le dijo: "Si no trabajas, no podrás quedarte en la colmena. Esta noche, cuando las puertas se cierren, quedarás afuera."\n\nLa abeja haragana no le dio importancia. Pero esa noche, cuando quiso entrar, las puertas estaban cerradas. Entonces comprendió su error. Tuvo que pasar la noche sola en una flor.\n\nA la mañana siguiente, la abeja haragana comenzó a trabajar como las demás. Aprendió que en la comunidad, cada uno debe hacer su parte.', nota: '' },
      { texto: 'EL LORO PELADO\n\nHabía una vez un loro que tenía las plumas más brillantes de la selva. Tanto le gustaba exhibirlas que se pasaba el día peinándoselas y mirándose en el río.\n\nUn día hubo un incendio en la selva. Todos los animales huyeron, pero el loro se quedó mirándose en el reflejo del agua. Cuando quiso escapar, el fuego ya era muy grande. Voló entre las llamas y se salvó, pero perdió todas sus plumas.\n\nDesde entonces el loro fue "el loro pelado". Se sentía muy avergonzado. Pero los otros animales le dijeron: "No importa cómo te veas por fuera, sino lo que eres por dentro."', nota: '' },
    ],
    portada: _p('Cuentos de','la Selva','Horacio Quiroga','#2e7d32','#a5d6a7','○'), creado: 'Clásico Argentino', ultimaPag: 0, marcadores: [], palabras: 380, fuente: 'precargado'
  },

  {
    id: 'pre_becquer',
    titulo: 'Rimas y Leyendas',
    autor: 'Gustavo Adolfo Bécquer',
    paginas: [
      { texto: 'RIMAS Y LEYENDAS\nGustavo Adolfo Bécquer\n\nRIMA I\n\nYo sé un himno gigante y extraño\nque anuncia en la noche del alma una aurora,\ny estas páginas son de ese himno\ncadencias que el aire dilata en las sombras.\n\nYo quisiera escribirle, del hombre\ndomando el rebelde, mezquino idioma,\ncon palabras que fuesen a un tiempo\nsuspiros y risas, colores y notas.\n\nPero en vano es luchar; que no hay cifra\ncapaz de encerrarlo, y apenas ¡oh hermosa!\nsi, teniendo en mis manos las tuyas,\npudiera, al oído, cantártelo a solas.', nota: '' },
      { texto: 'RIMA IV\n\nNo digáis que, agotado su tesoro,\nde asuntos falta, enmudeció la lira;\npodrá no haber poetas; pero siempre\nhabrá poesía.\n\nMientras las ondas de la luz al beso\npalpiten encendidas;\nmientras el sol las desgarradas nubes\nde fuego y oro vista;\nmientras el aire en su regazo lleve\nperfumes y armonías;\nmientras haya en el mundo primavera,\n¡habrá poesía!\n\nRIMA XXI\n\n¿Qué es poesía? —dices mientras clavas\nen mi pupila tu pupila azul—.\n¿Qué es poesía? ¿Y tú me lo preguntas?\nPoesía... eres tú.', nota: '' },
      { texto: 'LA LEYENDA DE LOS OJOS VERDES\n\nHace mucho tiempo que tenía ganas de escribir algo con este título. Hoy, que se me ha presentado ocasión, lo hago con placer. La razón es que nada me seduce como lo poético, lo indefinido, lo vago.\n\nFernando de Argensola halló, un día de verano, a orillas de un lago, a una mujer de inusitada belleza. Sus ojos eran de un color que Fernando nunca antes había visto: el color del agua profunda, verde, transparente, luminosa.\n\nLa joven lo miró con una fijeza extraña, y una sonrisa apenas perceptible se dibujó en sus labios. Desde ese momento, Fernando no pudo olvidarla. Volvió al lago una y otra vez, buscando esos ojos verdes que lo habían atrapado para siempre.', nota: '' },
    ],
    portada: _p('Rimas','y Leyendas','Gustavo A. Bécquer','#ad1457','#f48fb1','♫'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 310, fuente: 'precargado'
  },

  {
    id: 'pre_celestina',
    titulo: 'La Celestina',
    autor: 'Fernando de Rojas',
    paginas: [
      { texto: 'LA CELESTINA\nFernando de Rojas — 1499\n\nACTO PRIMERO\n\nCALISTO.— En esto veo, Melibea, la grandeza de Dios.\nMELIBEA.— ¿En qué, Calisto?\nCALISTO.— En dar poder a natura que de tan perfecta hermosura te dotase, y hacer a mí, inmérito, tanta merced que verte alcanzase, y en tan conveniente lugar, que mi secreto dolor manifestarte pudiese.\nMELIBEA.— Por gran premio tienes éste, Calisto.\nCALISTO.— Téngolo por tanto, en verdad, que si Dios me diese en el cielo la silla sobre sus santos, no lo ternía por tanta felicidad.', nota: '' },
      { texto: 'SEMPRONIO.— ¿Qué es esto? ¿Qué cosa puede ser ésta tan grave que haya echo perder el color que en la cara traes?\nCALISTO.— ¡Vete de aquí! No me hables; si no, quizá ante del tiempo de mi rabiosa muerte mis manos causarán tu arrebatado fin.\nSEMPRONIO.— Iré, pues solo quieres penar. ¡Oh soberano Dios! ¡Cuán altos son tus misterios! ¡Cuánta premia pusiste en el amor!\n\nLa Celestina, la vieja hechicera, entra en escena. Es ella quien mediará entre Calisto y Melibea, movida por el dinero. Su figura domina la obra: astuta, pragmática, sin escrúpulos, pero dotada de una vitalidad y una sabiduría que la convierten en uno de los personajes más fascinantes de la literatura española.', nota: '' },
      { texto: 'CELESTINA.— Todo lo puedo, todo lo sé, todo lo entiendo. Esta vieja que aquí ves ha hecho temblar a los más poderosos de esta ciudad. Con mi lengua y mis artes, he unido lo que parecía imposible unir.\n\nLa Celestina es la primera gran obra de la literatura española que no es ni poesía épica ni teatro sacro: es el retrato de una sociedad, con sus hipocresías, sus deseos, sus miedos y sus vicios.\n\nEl final es trágico para todos: Celestina muere a manos de sus cómplices; Calisto cae de una escalera; Melibea se arroja desde una torre. El amor que prometía todo acaba destruyendo todo.', nota: '' },
    ],
    portada: _p('La Celestina','','Fernando de Rojas','#6d4c41','#d7ccc8','◆'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_lazarillo',
    titulo: 'Lazarillo de Tormes',
    autor: 'Anónimo',
    paginas: [
      { texto: 'LAZARILLO DE TORMES\nAnónimo — 1554\n\nTRATADO PRIMERO\nCuenta Lázaro su vida y cuyo hijo fue\n\nPues sepa Vuestra Merced ante todas cosas que a mí llaman Lázaro de Tormes, hijo de Tomé González y de Antona Pérez, naturales de Tejares, aldea de Salamanca. Mi nacimiento fue dentro del río Tormes, por la cual causa tomé el sobrenombre.\n\nSiendo yo niño de ocho años, achacaron a mi padre ciertas sangrías mal hechas en los costales de los que allí a moler venían, por lo cual fue preso, y confesó y no negó, y padeció persecución por justicia.', nota: '' },
      { texto: 'Mi viuda madre, como sin marido y sin abrigo se viese, determinó arrimarse a los buenos por ser uno dellos, y vínose a vivir a la ciudad y alquiló una casilla y metióse a guisar de comer a ciertos estudiantes.\n\nElla y un hombre moreno de aquellos que las bestias curaban vinieron en conocimiento. Éste algunas veces se venía a nuestra casa y se iba a la mañana; otras veces de día llegaba a la puerta en achaque de comprar huevos y entrábase en casa.\n\nAl principio de su entrada pesábame a mí y habíale mala voluntad, viendo las colaciones que a mi madre hacía; mas de que vi que con su venida mejoraba el comer, fuile queriendo bien.', nota: '' },
      { texto: 'EL CIEGO\n\nFue mi madre a un hidalgo que estaba en la Iglesia Mayor, que se llamaba el señor ciego. Este ciego me tomó por suyo. Como este Lázaro vio que tenía habilidad, hízome su mozo.\n\nEl ciego era astuto y lleno de avisos. Si topaba con algún hombre que le pedía se sirviese de él para lo que le mandase, él le respondía: "¡Tomaremos que servís para poco!"\n\nLo que yo sufrí de aquel mal ciego, Dios se lo perdone; que con todo su saber me mataba de hambre. Si no fuera por ciertas cositas, habilidades que aprendí para comer, muchas veces me muriera de hambre.', nota: '' },
    ],
    portada: _p('Lazarillo','de Tormes','Anónimo','#37474f','#b0bec5','◇'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_romeo',
    titulo: 'Romeo y Julieta',
    autor: 'William Shakespeare',
    paginas: [
      { texto: 'ROMEO Y JULIETA\nWilliam Shakespeare\nTraducción al español\n\nPRÓLOGO\n\nDos familias, iguales en dignidad,\nen la hermosa Verona donde situamos nuestra escena,\npor antiguo rencor vuelven a la lucha,\ntiñendo con sangre civil las manos de ciudadanos.\n\nDe las entrañas fatales de estos dos enemigos\nnacieron dos amantes marcados por las estrellas;\nsu desventurado y lamentable fin\nentierra con su muerte las querellas de sus padres.', nota: '' },
      { texto: 'ACTO SEGUNDO — ESCENA SEGUNDA — EL BALCÓN\n\nROMEO.— [Mirando hacia la ventana] ¿Qué luz es ésa que se abre paso por aquella ventana? Es el Oriente, y Julieta es el sol. ¡Alza, bello sol! Es mi dama, ¡oh!, es mi amor. ¡Ojalá lo supiera ella!\n\nJULIETA aparece en el balcón.\n\nROMEO.— Dos de las más bellas estrellas del cielo, teniendo que ausentarse, ruegan a sus ojos que brillen en su lugar hasta que vuelvan.\n\nJULIETA.— ¡Ay de mí!\nROMEO.— Habla. ¡Oh! habla otra vez, ángel resplandeciente.', nota: '' },
      { texto: 'JULIETA.— ¡Oh Romeo, Romeo! ¿Por qué eres tú Romeo? Reniega de tu padre y niega tu nombre; o, si no quieres, júrame tan solo que me amas, y dejaré yo de ser una Capuleto.\n\nROMEO.— [Aparte] ¿Le hablaré, o esperaré oír más?\n\nJULIETA.— Solo tu nombre es mi enemigo. Tú eres tú mismo, seas o no Montesco. ¿Qué es Montesco? No es ni mano, ni pie, ni brazo, ni rostro, ni parte alguna del cuerpo humano. ¡Oh, toma otro nombre! ¿Qué tiene un nombre? Lo que llamamos rosa con cualquier otro nombre olería igualmente dulce.', nota: '' },
    ],
    portada: _p('Romeo y Julieta','','William Shakespeare','#1a237e','#9fa8da','♡'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_divina',
    titulo: 'La Divina Comedia',
    autor: 'Dante Alighieri',
    paginas: [
      { texto: 'LA DIVINA COMEDIA\nDante Alighieri — 1304-1321\nTraducción al español\n\nINFIERNO — CANTO PRIMERO\n\nA la mitad del camino de nuestra vida\nme encontré en una selva oscura,\nporque la senda recta se había perdido.\n\n¡Ay, cuán difícil es describir\ncómo era aquella selva áspera y espesa\ncuyo recuerdo renueva el miedo!\n\nEs tan amargo que la muerte apenas lo es más;\npero para tratar del bien que allí encontré,\nhe de hablar de otras cosas que allí vi.', nota: '' },
      { texto: 'No sé decir bien cómo entré en ella,\ntan lleno estaba de sueño en aquel momento\nen que abandoné el verdadero camino.\n\nPero cuando llegué al pie de una colina,\nalcé los ojos y vi sus hombros\nvestidos ya con los rayos del planeta\nque guía a los hombres por todo camino recto.\n\nEntonces se calmó un poco el miedo\nque había durado en el lago de mi corazón\nla noche que pasé con tanta angustia.\n\nY como el que con aliento jadeante\nha salido del mar a la orilla,\nse vuelve hacia el agua peligrosa y la contempla,\nasí mi ánimo, que aún huía,\nse volvió a mirar el paso que jamás dejó vivo a nadie.', nota: '' },
      { texto: 'CANTO TERCERO — LA PUERTA DEL INFIERNO\n\nPOR MÍ SE VA A LA CIUDAD DEL LLANTO,\nPOR MÍ SE VA AL DOLOR ETERNO,\nPOR MÍ SE VA HACIA LA GENTE PERDIDA.\n\nLA JUSTICIA MOVIÓ A MI EXCELSO HACEDOR;\nME HICIERON LA DIVINA POTESTAD,\nLA SUMA SABIDURÍA Y EL PRIMER AMOR.\n\nANTES QUE YO NO HABÍA COSAS CREADAS\nSINO ETERNAS, Y YO ETERNO DURO.\n¡VOSOTROS QUE ENTRÁIS, ABANDONAD TODA ESPERANZA!\n\nMaestro, estas palabras son duras para mí.\nY él, como hombre experimentado, me respondió:\nAquí conviene dejar todo recelo;\nconviene que aquí muera toda cobardía.', nota: '' },
    ],
    portada: _p('La Divina','Comedia','Dante Alighieri','#311b92','#b39ddb','∞'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_iliada',
    titulo: 'La Ilíada',
    autor: 'Homero',
    paginas: [
      { texto: 'LA ILÍADA\nHomero\nTraducción al español\n\nCANTO PRIMERO\n\nCanta, oh diosa, la cólera del Pelida Aquiles,\ncólera funesta que causó infinitos males a los aqueos\ny precipitó al Hades muchas almas valerosas de héroes,\ny a ellos mismos los hizo presa de perros\ny de toda clase de aves —y así se cumplía la voluntad de Zeus—\ndesde que se separaron disputando\nAtrida, rey de hombres, y el divino Aquiles.', nota: '' },
      { texto: '¿Cuál de los dioses los puso en esa discordia y querella?\nEl hijo de Leto y de Zeus, Apolo. Pues indignado con el rey,\nsuscitó en el ejército una maligna epidemia\ny los hombres perecían, porque el Atrida había afrentado\na Crises, sacerdote de Apolo.\n\nEste había llegado a las veloces naves de los aqueos\na rescatar a su hija y traía un cuantioso rescate,\nostentando las insignias de Apolo el que hiere de lejos\nen el cetro de oro y la cinta sagrada.', nota: '' },
      { texto: 'Atridas y demás aqueos de hermosas grebas:\nos quieran los dioses que moran en los palacios del Olimpo\nconcederos destruir la ciudad de Príamo y regresar felizmente a casa;\npero liberad a mi hija y aceptad el rescate,\nrespetando al hijo de Zeus, Apolo el que hiere de lejos.\n\nEntonces todos los aqueos asintieron con aclamaciones,\nrespetando al sacerdote y aceptando el glorioso rescate.\nPero no fue del agrado del Atrida Agamenón,\nque lo despidió duramente y añadió graves palabras:\nNo te encuentre yo, anciano, junto a las cóncavas naves,\nni ahora mientras te demoras ni si vuelves de nuevo.', nota: '' },
    ],
    portada: _p('La Ilíada','','Homero','#4a3728','#f9a825','★'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 290, fuente: 'precargado'
  },

  {
    id: 'pre_poe',
    titulo: 'Cuentos — Edgar Allan Poe',
    autor: 'Edgar Allan Poe',
    paginas: [
      { texto: 'EL CORAZÓN DELATOR\nEdgar Allan Poe\nTraducción al español\n\n¡Es verdad! Soy nervioso, muy nervioso, terriblemente nervioso, y siempre lo he sido; pero ¿por qué afirmáis que estoy loco? La enfermedad había agudizado mis sentidos, no los había destruido. Tenía el oído muy fino. Oía todas las cosas del cielo y de la tierra. ¿Cómo podía estar loco? Escuchad y observad con cuánta cordura puedo contaros toda la historia.', nota: '' },
      { texto: 'Es imposible decir cómo la idea entró primeramente en mi cerebro; pero, una vez concebida, me obsesionó noche y día. No había objeto. No había pasión. Amaba al viejo. Nunca me había hecho ningún mal. Creo que fue su ojo —el ojo de un buitre, un ojo pálido azulado con una película sobre él. Cada vez que se posaba sobre mí, se me helaba la sangre, y así, lentamente, se me fue metiendo en la cabeza la idea de quitarle la vida al viejo para librarme para siempre de aquel ojo.', nota: '' },
      { texto: 'LA MÁSCARA DE LA MUERTE ROJA\n\nLa Muerte Roja había devastado el país durante largo tiempo. Jamás pestilencia alguna fue tan fatal ni tan espantosa. La sangre era su sello distintivo y su emblema.\n\nSentíanse agudos dolores, un vértigo repentino y luego brotaba un sudor abundante por los poros, y de esto resultaba la disolución del ser. Las manchas escarlatas en el cuerpo de la víctima eran el bando que la ponía fuera del socorro y de la simpatía de sus semejantes.\n\nSin embargo, el Príncipe Próspero era feliz e intrépido y sagaz. Cuando sus dominios quedaron semidespoblados, convocó a un millar de caballeros y damas para recluirse en una de sus abadías.', nota: '' },
    ],
    portada: _p('Cuentos','','Edgar Allan Poe','#1e1b4b','#a5b4fc','◆'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

  {
    id: 'pre_zaratustra',
    titulo: 'Así habló Zaratustra',
    autor: 'Friedrich Nietzsche',
    paginas: [
      { texto: 'ASÍ HABLÓ ZARATUSTRA\nFriedrich Nietzsche — 1883\nTraducción al español\n\nDEL PRÓLOGO DE ZARATUSTRA\n\nCuando Zaratustra tenía treinta años, abandonó su tierra natal y se fue a las montañas. Allí gozó de su espíritu y de su soledad durante diez años. Pero al fin su corazón se transformó, y una mañana se levantó con la aurora, se puso delante del sol y le habló así:\n\n"¡Gran astro! ¿Qué sería de tu felicidad si no tuvieras a aquellos a quienes iluminas?"', nota: '' },
      { texto: '"He aquí que estoy harto de mi sabiduría, como la abeja que ha recogido demasiada miel; necesito manos que se extiendan hacia mí.\n\nQuisiera regalar y distribuir hasta que los sabios de entre los hombres hayan vuelto a gozarse en su locura y los pobres en su riqueza.\n\nPara ello debo descender a las profundidades: como lo haces tú al atardecer cuando te hundes detrás del mar y llevas tu luz incluso al mundo subterráneo, ¡astro exuberante!\n\nComo tú, debo declinar, como dicen los hombres a quienes quiero bajar."', nota: '' },
      { texto: 'DE LAS TRES TRANSFORMACIONES\n\nTres transformaciones del espíritu os menciono:\ncómo el espíritu se convierte en camello,\nel camello en león,\ny el león, por último, en niño.\n\nEl espíritu-camello carga con lo más pesado, lo que más duele, lo que más exige. El espíritu-camello dice: "Sí, lo cargo."\n\nEl espíritu-león conquista la libertad: dice "No" a los viejos valores. Pero no puede crear valores nuevos.\n\nEl espíritu-niño crea valores nuevos: es inocencia, olvido, un nuevo comienzo, un juego, una rueda que gira por sí misma.\n\nPara el juego del crear, hermanos míos, se necesita un santo decir "Sí".', nota: '' },
    ],
    portada: _p('Así habló','Zaratustra','Friedrich Nietzsche','#450a0a','#fca5a5','◇'), creado: 'Clásico', ultimaPag: 0, marcadores: [], palabras: 300, fuente: 'precargado'
  },

];
